# Generated by Django 4.1.2 on 2022-12-27 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reseller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reseller',
            name='status',
            field=models.CharField(default='pending', max_length=12),
        ),
    ]
