# Generated by Django 4.1.2 on 2022-12-27 09:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reseller', '0002_reseller_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_category', models.CharField(max_length=40)),
                ('p_name', models.CharField(max_length=40)),
                ('p_number', models.BigIntegerField()),
                ('p_price', models.BigIntegerField()),
                ('p_discription', models.CharField(max_length=500)),
                ('p_stock', models.BigIntegerField()),
                ('p_image', models.ImageField(upload_to='product/')),
                ('date', models.DateField(default=datetime.date.today)),
                ('seller_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reseller.reseller')),
            ],
        ),
    ]
